# Coreapp policy for JWT Verification
apiVersion: "authentication.istio.io/v1alpha1"
kind: "Policy"
metadata:
  name: "app-layer-jwt"
spec:
  targets:
    - name: applayer-policy
  origins:
    - jwt:
        issuer: "https://ic-dot-dogeictest.appspot.com/"
        jwksUri: "https://ic-dot-dogeictest.appspot.com/.well-known/jwks.json"
  principalBinding: USE_ORIGIN