# Copyright 2017 Istio Authors
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

##################################################################################################
# kernel1 service
##################################################################################################
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kernel1
---
apiVersion: v1
kind: Service
metadata:
  name: kernel1
  labels:
    app: kernel1
spec:
  ports:
    - name: http
      port: 8001
      targetPort: 5000
  selector:
    app: kernel1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kernel1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kernel1
      version: v1
  template:
    metadata:
      labels:
        app: kernel1
        version: v1
    spec:
      serviceAccountName: kernel1
      containers:
        - image: docker.io/yonghao/applayer_app
          imagePullPolicy: Always
          name: kernel1
          ports:
            - containerPort: 5000