# Kernel1 policy to enable mutual TLS
apiVersion: "authentication.istio.io/v1alpha1"
kind: "Policy"
metadata:
  name: "kernel1-policy"
  namespace: dev
spec:
  targets:
    - name: kernel1
  peers:
    - mtls: {}
---

# Kernel1 destination rule
apiVersion: "networking.istio.io/v1alpha3"
kind: "DestinationRule"
metadata:
  name: "kernel1"
  namespace: "dev"
spec:
  host: "kernel1.dev.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
---
# AuthZ Policy
apiVersion: "security.istio.io/v1beta1"
kind: "AuthorizationPolicy"
metadata:
  name: "kernel1-access"
  namespace: dev
spec:
  selector:
    matchLabels:
      app: kernel1
      version: v1
  rules:
    - from:
        - source:
            principals: ["cluster.local/ns/dev/sa/coreapp111"]
      to:
        - operation:
            methods: ["GET"]