# Define a rule to reject all request if oidc_access_token is presented in request header.
apiVersion: "config.istio.io/v1alpha2"
kind: denier
metadata:
  name: denyall
  namespace: dev
spec:
  status:
    code: 7
    message: Not allowed
---
apiVersion: "config.istio.io/v1alpha2"
kind: checknothing
metadata:
  name: denyoidc
  namespace: dev
spec:
---
apiVersion: "config.istio.io/v1alpha2"
kind: rule
metadata:
  name: denyreviewsv3
  namespace: dev
spec:
  match: destination.labels["app"] == "coreapp" && match(request.headers["oidc_access_token"], "*")
  actions:
    - handler: denyall.denier
      instances: [ denyoidc.checknothing ]
